// Projects and case studies. `caseStudy: true` entries get a page at /projects/[slug].

export const projects = [
  {
    slug: 'rootcause',
    name: 'RootCause',
    kind: 'Multi-Agent SRE Assistant',
    caseStudy: true,
    featured: true,
    accent: ['#8B5CF6', '#22D3EE'],
    year: '2026',
    tagline: 'An agent that finds out why, not just what, and can’t touch production without a recorded human approval.',
    summary:
      'Diagnoses infrastructure incidents through a plan → execute → verify agent loop against a demo microservices stack with genuinely injected faults: container kills, network latency, connection-pool exhaustion.',
    repo: 'https://github.com/aziz-05/rootcause-agent',
    evalCmd: 'python -m eval.runner --offline',
    stack: ['Python', 'LangGraph', 'FastAPI', 'PostgreSQL', 'pgvector', 'Redis', 'Docker', 'Kubernetes', 'OpenTelemetry', 'Prometheus', 'Jaeger', 'Grafana'],
    metrics: [
      { value: '53', label: 'tests' },
      { value: '23', label: 'invariant checks on every PR' },
      { value: '5', label: 'real fault scenarios' },
      { value: '0', label: 'writes without approval' },
    ],
    highlights: [
      'Write actions require recorded human approval, enforced in code and in the database. The approvals row authorises an action, not the agent’s in-memory flag.',
      'A fixed, parameterised tool registry and Kubernetes RBAC (four verbs, two resource types, one namespace) limit what remediation can ever do. There is no run_shell tool.',
      'A 23-check invariant gate runs on every pull request, including adversarial prompt-injection cases that script a maximally credulous model and assert no write executes anyway.',
      'Interruptible state machine: Triage → Diagnose → Plan → ApprovalGate → Execute → Verify → Report. It suspends for a human instead of blocking a thread, and survives restarts.',
      'Bounded retries escalate to a human after 3 failed verifications instead of looping forever.',
      'Full audit trail: every agent step and tool call is persisted with its arguments and result, and streamed live over SSE.',
    ],
    problems: [
      ['Write actions need human approval', 'execute_tool_call() raises ApprovalRequired unless an approvals row says approved'],
      ['No arbitrary command execution', 'Fixed, parameterised tool registry. is_write comes from the registry, never from the model'],
      ['Agents loop forever', 'register_retry() escalates to a human after 3 failed verifications'],
      ['“What did the agent do?”', 'agent_events + tool_calls tables persist every step, streamed over SSE'],
      ['Diagnosis must be read-only', 'The telemetry client exposes no method that can mutate the observed system'],
    ],
    flow: [
      { label: 'Alert', sub: 'Alertmanager webhook' },
      { label: 'Triage', sub: 'scope the incident' },
      { label: 'Diagnose', sub: 'metrics · traces · logs' },
      { label: 'Plan', sub: 'propose remediation' },
      { label: 'Approval', sub: 'human in the loop', gate: true },
      { label: 'Execute', sub: 'scoped RBAC tools' },
      { label: 'Verify', sub: 'did it actually heal?' },
      { label: 'Report', sub: 'postmortem' },
    ],
    evals: [
      ['escalation_correctness', '100.0%', '1.00', 'pass (3/3)'],
      ['injection_containment', '100.0%', '—', '(4/4)'],
      ['remediation_correctness', '100.0%', '0.80', 'pass (5/5)'],
      ['tool_call_correctness', '100.0%', '0.85', 'pass (5/5)'],
      ['unsafe_action_rate', '100.0%', '1.00', 'pass (6/6)'],
    ],
  },
  {
    slug: 'souk-copilot',
    name: 'Souk Copilot',
    kind: 'Production RAG & Analytics Platform',
    caseStudy: true,
    featured: true,
    accent: ['#22D3EE', '#A3E635'],
    year: '2026',
    tagline: 'Ask a marketplace’s policies and data one question at a time. Every answer is cited or refused.',
    summary:
      'Routes policy and analytics questions to a retrieval or text-to-SQL path, refusing rather than guessing below a relevance floor. Citations are bound to the exact source chunk.',
    repo: 'https://github.com/aziz-05/souk-copilot',
    evalCmd: 'python -m packages.eval_harness.runner --offline',
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'pgvector', 'Redis', 'Docker', 'OpenAI', 'Azure OpenAI', 'sqlglot', 'Prometheus'],
    metrics: [
      { value: '103', label: 'tests' },
      { value: '100%', label: 'routing accuracy (22/22)' },
      { value: '100%', label: 'recall@5 on golden set' },
      { value: '0', label: 'uncited answers shipped' },
    ],
    highlights: [
      'Hybrid retrieval: BM25 for exact tokens like policy IDs and reason codes, embeddings for paraphrase, fused with reciprocal rank fusion and reranked.',
      'Section-aware chunking keeps the heading trail on every chunk, so a citation names a real clause.',
      'A cite-or-refuse gate runs after generation. An answer with no citation becomes a refusal, and no prompt can talk it out of that rule.',
      'Generated SQL is treated as untrusted code: AST-validated with sqlglot, CTE-aware, LIMIT-clamped, and executed as a role with SELECT on three views and nothing else.',
      'JWT with a pinned algorithm and row-level isolation. Internal playbooks are filtered by viewer role, never cited to sellers.',
      'CI-gated evaluation on recall@k, MRR, refusal correctness and groundedness, so retrieval can’t silently get worse.',
    ],
    problems: [
      ['Models answer confidently without evidence', 'compose_answer() refuses any answer carrying no citation, enforced after generation'],
      ['Generated SQL is untrusted code', 'Parsed with sqlglot, checked structurally, run as a read-only role on three views'],
      ['Vector search misses exact tokens', 'BM25/trigram + embeddings fused with RRF'],
      ['Chunking destroys citations', 'Section-aware chunks keep the heading trail'],
      ['Internal docs leak to customers', 'Citations filtered by viewer role, not by asking the model nicely'],
      ['Prompt injection', 'Injection markers refuse at routing; a refused route discards generated text'],
    ],
    flow: [
      { label: 'Question', sub: '+ viewer role' },
      { label: 'Router', sub: 'refuse injection / writes', gate: true },
      { label: 'Hybrid search', sub: 'BM25 + vector → RRF' },
      { label: 'Rerank', sub: 'relevance floor' },
      { label: 'Text-to-SQL', sub: 'AST-validated, read-only' },
      { label: 'Cite-or-refuse', sub: 'no citation → no answer', gate: true },
      { label: 'Answer', sub: 'citations + trace' },
    ],
    evals: [
      ['data_isolation', '100.0%', '1.00', 'pass (1/1)'],
      ['near_miss_avoidance', '100.0%', '1.00', 'pass (1/1)'],
      ['refusal_accuracy', '100.0%', '1.00', 'pass (4/4)'],
      ['retrieval_recall_at_5', '100.0%', '0.90', 'pass (10/10)'],
      ['routing_accuracy', '100.0%', '0.90', 'pass (22/22)'],
    ],
  },
  {
    slug: 'ouedkniss',
    name: 'Ouedkniss Marketplace',
    kind: 'Professional · Full Stack',
    year: '2023 – now',
    accent: ['#F59E0B', '#EF4444'],
    summary:
      'Microservices, REST/GraphQL APIs and React/Vue front-ends for Algeria’s largest classifieds marketplace. Event-driven processing with RabbitMQ, Keycloak SSO, and Kubernetes delivery via GitLab CI/CD.',
    stack: ['NestJS', 'Laravel', 'Node.js', 'Vue.js 3', 'React', 'RabbitMQ', 'Keycloak', 'Kubernetes'],
    link: 'https://www.ouedkniss.com',
    linkLabel: 'ouedkniss.com',
  },
  {
    slug: 'qos-aodv',
    name: 'QoS-AODV',
    kind: 'Research · MSc Thesis',
    year: '2021',
    accent: ['#6366F1', '#EC4899'],
    summary:
      'A quality-of-service aware extension of the AODV routing protocol for vehicular ad-hoc networks (VANETs), improving delay, bandwidth and packet loss. Simulated in NS-2 with C++.',
    stack: ['C++', 'NS-2', 'VANET', 'Routing protocols'],
    link: '/posts/qos-aodv-vanet',
    linkLabel: 'Read the write-up',
  },
  {
    slug: 'emodec',
    name: 'EMODEC',
    kind: 'Research · BSc Project',
    year: '2019',
    accent: ['#10B981', '#22D3EE'],
    summary:
      'A speech-emotion recognition API that classifies the emotional state of a speaker from raw audio using deep-learning features.',
    stack: ['Python', 'Deep Learning', 'Audio features', 'REST API'],
  },
];

export const caseStudies = projects.filter((p) => p.caseStudy);
export const getProject = (slug) => projects.find((p) => p.slug === slug);

// Earlier front-end projects that are still live.
export const liveProjects = [
  {
    title: "Portfolio v1",
    image: "/images/portfolio.jpg",
    tech: ["React", "Next.js", "Styled Components"],
    repo: "https://github.com/aziz-05/abd_elaziz-_hafallah",
    live: "https://abd-elaziz-hafallah.vercel.app/",
  },
  {
    title: "React Shop",
    image: "/images/react-store.jpg",
    tech: ["React", "Redux", "Styled Components", "GraphQL"],
    repo: "https://github.com/aziz-05/react-clothing-main",
    live: "https://react-clothing-main.vercel.app/",
  },
  {
    title: "Amazon Clone",
    image: "/images/amazon-clone.jpg",
    tech: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/aziz-05/javascript-amazon-project-main",
    live: "https://amazin-clone-sigma.vercel.app/",
  },
  {
    title: "WatchVid",
    image: "/images/watchvid.jpg",
    tech: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/aziz-05/watchvid",
    live: "https://watchvid.vercel.app/",
  },
  {
    title: "Spotify Clone",
    image: "/images/sptify-clone.jpg",
    tech: ["React", "Axios", "JavaScript", "HTML", "CSS"],
    repo: "https://github.com/aziz-05/Sportify-main",
    live: "https://sportify-main.vercel.app/",
  },
];
